import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useStore } from '@/store/useStore'
import type { Invoice } from '@/store/useStore'
import { InvoiceForm } from './invoice/InvoiceForm'
import { InvoicePreview } from './invoice/InvoicePreview'
import { Button } from '@/components/ui/button'
import { PDFDownloadLink } from '@react-pdf/renderer'
import { InvoicePDF } from '@/components/pdf/InvoicePDF'
import { MinimalInvoicePDF } from '@/components/pdf/MinimalInvoicePDF'
import { CreativeInvoicePDF } from '@/components/pdf/CreativeInvoicePDF'
import { ElegantInvoicePDF } from '@/components/pdf/ElegantInvoicePDF'
import { BoldInvoicePDF } from '@/components/pdf/BoldInvoicePDF'
import { ArrowLeft, MoreVertical } from 'lucide-react'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'

export function InvoiceEditor() {
    const { id } = useParams()
    const navigate = useNavigate()
    const { invoices, firms, addInvoice, updateInvoice, activeFirmId } = useStore()

    const [invoiceContext, setInvoiceContext] = useState<Partial<Invoice>>({
        id: window.crypto.randomUUID(),
        invoiceNo: `INV-${Date.now()}`,
        date: new Date().toISOString().split('T')[0],
        firmId: activeFirmId || '',
        items: [],
        subtotal: 0,
        taxType: 'CGST_SGST',
        taxAmount: 0,
        grandTotal: 0,
        status: 'Draft'
    })

    const currentFirm = firms.find(f => f.id === invoiceContext.firmId)

    useEffect(() => {
        if (id) {
            const existing = invoices.find(inv => inv.id === id)
            if (existing) setInvoiceContext(existing)
        }
    }, [id, invoices])

    const lastAutoGeneratedNo = useRef<string | null>(null);

    useEffect(() => {
        if (!id && invoiceContext.firmId) {
            const firm = firms.find(f => f.id === invoiceContext.firmId);
            if (firm) {
                const initials = firm.name.trim().split(/\s+/).map(w => w[0]?.toUpperCase()).join('').substring(0, 3) || 'INV';
                const year = new Date().getFullYear().toString().slice(-2);
                const prefix = `${initials}-${year}`;

                let maxSeq = 0;
                invoices.forEach(inv => {
                    if (inv.firmId === firm.id && !!inv.invoiceNo && inv.invoiceNo.startsWith(prefix)) {
                        const numStr = inv.invoiceNo.replace(prefix, '');
                        const num = parseInt(numStr, 10);
                        if (!isNaN(num) && num > maxSeq) maxSeq = num;
                    }
                });

                const nextSeq = (maxSeq + 1).toString().padStart(5, '0');
                const nextInvoiceNo = `${prefix}${nextSeq}`;

                setInvoiceContext(prev => {
                    // Check if it's the initial placeholder, tracking identical to last generation, or blank
                    const isUnmodified = prev.invoiceNo?.startsWith('INV-') || prev.invoiceNo === lastAutoGeneratedNo.current || !prev.invoiceNo;
                    const computedNo = isUnmodified ? nextInvoiceNo : prev.invoiceNo;

                    if (isUnmodified) {
                        lastAutoGeneratedNo.current = nextInvoiceNo;
                    }

                    if (prev.invoiceNo !== computedNo || (!prev.template && firm.defaultTemplate)) {
                        return {
                            ...prev,
                            invoiceNo: computedNo,
                            template: prev.template || firm.defaultTemplate || 'standard'
                        };
                    }
                    return prev;
                });
            }
        }
    }, [id, invoiceContext.firmId, firms, invoices]);

    const handleSave = (status: 'Draft' | 'Pending' | 'Paid' = 'Draft') => {
        if (!invoiceContext.firmId) {
            alert("Please select a Firm first.");
            return;
        }
        const finalInvoice = { ...invoiceContext, status } as Invoice
        if (id && invoices.find(inv => inv.id === id)) {
            updateInvoice(id, finalInvoice)
        } else {
            addInvoice(finalInvoice)
        }
        navigate('/')
    }

    return (
        <div className="flex flex-col h-full bg-slate-100 dark:bg-slate-950">
            {/* Header */}
            <header className="flex justify-between items-center p-4 bg-white dark:bg-slate-900 border-b shrink-0">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon" onClick={() => navigate('/')}><ArrowLeft className="w-5 h-5" /></Button>
                    <h1 className="text-xl font-bold">{id ? 'Edit Invoice' : 'New Invoice'}</h1>
                </div>
                <div className="flex gap-2">
                    <div className="hidden md:flex gap-2">
                        <Button variant="outline" onClick={() => handleSave('Draft')}>Save Draft</Button>
                        <Button variant="outline" onClick={() => handleSave('Pending')}>Save as Pending</Button>
                        <Button onClick={() => handleSave('Paid')}>Save Completed</Button>
                    </div>
                    <div className="md:hidden">
                        <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                                <Button variant="outline" size="icon"><MoreVertical className="w-5 h-5" /></Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                                <DropdownMenuItem onClick={() => handleSave('Draft')}>Save Draft</DropdownMenuItem>
                                <DropdownMenuItem onClick={() => handleSave('Pending')}>Save as Pending</DropdownMenuItem>
                                <DropdownMenuItem onClick={() => handleSave('Paid')}>Save Completed</DropdownMenuItem>
                            </DropdownMenuContent>
                        </DropdownMenu>
                    </div>
                    <PDFDownloadLink
                        document={
                            invoiceContext.template === 'elegant'
                                ? <ElegantInvoicePDF invoice={invoiceContext as Invoice} firm={currentFirm} />
                                : invoiceContext.template === 'bold'
                                    ? <BoldInvoicePDF invoice={invoiceContext as Invoice} firm={currentFirm} />
                                    : invoiceContext.template === 'creative'
                                        ? <CreativeInvoicePDF invoice={invoiceContext as Invoice} firm={currentFirm} />
                                        : invoiceContext.template === 'minimal'
                                            ? <MinimalInvoicePDF invoice={invoiceContext as Invoice} firm={currentFirm} />
                                            : <InvoicePDF invoice={invoiceContext as Invoice} firm={currentFirm} />
                        }
                        fileName={`${invoiceContext.invoiceNo || 'invoice'}.pdf`}
                    >
                        {({ loading }) => (
                            <Button variant="secondary" disabled={loading}>{loading ? 'Preparing...' : 'Download PDF'}</Button>
                        )}
                    </PDFDownloadLink>
                </div>
            </header>

            {/* Main Workspace */}
            <div className="flex-1 overflow-hidden grid grid-cols-1 lg:grid-cols-2">
                {/* Left: Form */}
                <div className="overflow-auto border-r bg-white dark:bg-slate-900 pb-12">
                    <InvoiceForm invoice={invoiceContext} setInvoice={setInvoiceContext} />
                </div>

                {/* Right: PDF Preview */}
                <div className="overflow-auto bg-slate-100 dark:bg-slate-950 pb-12">
                    <InvoicePreview invoice={invoiceContext as Invoice} firm={currentFirm} />
                </div>
            </div>
        </div>
    )
}
